version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/build
    overwrite: yes
permissions:
  - object: /home/ec2-user/build
    pattern: "**"
    owner: ec2-user
    group: ec2-user
hooks:
  ApplicationStart:
    - location: stop.sh
      timeout: 60
      runas: ec2-user